name: CMake

on:
 push:
  branches: [master]
  tags: -"v*1.*"
 pull_request:
  branches: [master]

env:

  BUILD_TYPE: Release
jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: cmake -H. -B_build -DCPACK_GENERATOR="TGZ"
    - run: cmake --build _build --target package 
    - run: cd _build && cpack -G "DEB" &&
    - run: cpack -G "RPM"
    - run: mkdir ../artifacts
    - run: mv *.tar.gz ../artifacts/
    - run: mv *.deb ../artifacts/
    - run: mv *.rpm ../artifacts/

    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: artifacts/

