name: CMake

on:
 push:
  branches: [test]
  tags: -"v*1.*"
 pull_request:
  branches: [test]

env:

  BUILD_TYPE: Release
jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: cmake -H. -B_build -DCPACK_GENERATOR="TGZ" && cmake --build _build --target package &&
             cmake -H -B_build -DCPACK_GENERATOR="DEB" && cmake --build _build --target package &&
             cd _build && cpack -G "RPM" &&
             mkdir ../artifacts &&
             mv *.tar.gz ../artifacts/ &&
             mv *.rpm ../artifacts/

    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: artifacts/

